### ISSUE TITLE
Empty value on click

### ISSUE THREAD

**Issue by federicocappellotto97** [tbleckert/react-select-search#139] opened 2020-12-01 21:58 UTC
If i click on an option the value of the select is empty.
I'm taking options through a fetch
`<SelectSearch
   options={[]}
   getOptions={(query) => {
     return new Promise((resolve, reject) => {
        fetch('http://www.omdbapi.com/?s='${query}')
            .then(response => response.json())
            .then(({ Search }) => {
                resolve(Search.map(({ imdbID, Title }) => ({ value: imdbID, name: Title })))
            })
            .catch(reject);
       });
   }}
   search
   emptyMessage="Nessun film trovato"
   autoComplete="off"
   name="movie"
   placeholder="Aggiungi un film"
   className="select"
/>`

![ezgif-2-1a4f6a189872](https://user-images.githubusercontent.com/63153191/100801773-be3df600-3428-11eb-9cd6-711796c2dd21.gif)

**Comment by federicocappellotto97** [comment] 2020-12-01 22:03
I see the same behavior in your examples [here](https://react-select-search.com/?path=/story/async--fetch)

**Comment by tbleckert** [comment] 2020-12-02 13:41
Looks like a duplicate of https://github.com/tbleckert/react-select-search/issues/89

**Closed by tbleckert** 2020-12-02 13:41 UTC

**Comment by federicocappellotto97** [comment] 2020-12-02 13:43
> Looks like a duplicate of #89

And where is the solution?

**Comment by tbleckert** [comment] 2020-12-02 13:45
@federicocappellotto97 In the upcoming v3 release, currently in the next branch. But will probably be patched in v2 as well.

**Comment by federicocappellotto97** [comment] 2020-12-02 13:46
> @federicocappellotto97 In the upcoming v3 release, currently in the next branch. But will probably be patched in v2 as well.

Is there any workaround?
