### ISSUE TITLE
input 'deselect'

### ISSUE THREAD

**Issue by abigwonderful** [tbleckert/react-select-search#3] opened 2016-04-27 15:52 UTC
Have a new issue that I'm hoping will be as quick to resolve as the last:

When I select an option the input is populated, but focus remains on the field and you can't actually see the text. If I click elsewhere on the page, then it shows, but without the click it makes for a wonky UX. Any thoughts?

**Comment by tbleckert** [comment] 2016-04-27 16:31
In which browser does this happen? Sounds like a bug if I don't misunderstand you. You should loose the focus when you select an option in the list. But I will fix it so the focus is kept but you should always see the value you selected (see #4)

**Comment by abigwonderful** [comment] 2016-04-27 17:15
chrome latest (Version 50.0.2661.86 (64-bit))
OSX 10.11.4 (15E65)

**Comment by abigwonderful** [comment] 2016-04-28 04:36
a screen capture of the funk i'm seeing

![screen cap](http://g.recordit.co/DHn3n2hIAL.gif)

**Comment by tbleckert** [comment] 2016-04-28 04:45
Hm ok, yes, that is a bug. Thanks for the demonstration, will take a look. Does the font selection in the demo page work for you? http://tbleckert.github.io/react-select-search/

**Comment by abigwonderful** [comment] 2016-04-28 05:15
Yes it does and actually after playing with its location on the page, I discovered that the issue lies in wrapping the component in <label> tags! Funny. no more issue with <label> removed. Easy fix, although i  don't fully understand why

**Comment by tbleckert** [comment] 2016-04-28 05:21
Nice, but it should of course work no matter what. Do you have some code you can share with me? The code you had when it was not working.

**Comment by abigwonderful** [comment] 2016-04-28 05:52
for what it's worth - using foundation6
```
<label>
  { this.props.users.length === 0 ? null :  
     <div className="input-group">
       <SelectSearch valueChanged={this.props.handleNewMem} options={this.props.users} ref="users" />
         <a id="add" onClick={() => { this.props.addMember(this.props.newMem, this.props.groupForm) }} className="input-group-button button">+ add</a>
     </div>
     }
</label>

**Comment by tbleckert** [comment] 2016-04-28 05:58
I think that it's the label that is the problem. Clicking a label sets focus to its connected input (input is connected either by `for`+`id` or by wrapping). So it's probably an event problem caused by the label.

Does it work if you wrap it with something different than a label?

Either way I will take a look at it, and this will possibly be fixed when #4 is solved

**Comment by abigwonderful** [comment] 2016-04-29 12:07
Yeah after sending that last comment I tried span, p, div and a few others without a problem. I think the inherent behavior of the label was the issue.

**Comment by tbleckert** [comment] 2016-06-18 10:13
I'm closing this one. I've released a new version with better focus handling. I decided to not this specific scenario but with the new focus handling you will be able to choose an option, even if the component is wrapped in a label. The only difference is that the dropdown won't close, since the label will reset the focus on the search field.

**Closed by tbleckert** 2016-06-18 10:13 UTC
Labels: bug

**Comment by abigwonderful** [comment] 2016-06-20 15:46
Sounds good!
