### ISSUE TITLE
Multiselect: when you press enter on option it triggers submit for example.

### ISSUE THREAD

**Issue by agustingabiola** [tbleckert/react-select-search#123] opened 2020-10-06 20:29 UTC
Thanks for the latest improvements @tbleckert Though I found a regression maybe. When you press enter on an option while doing multi-select, the event bubbles up so adding a preventDefault/stopPropagation should fix this.

**Comment by tbleckert** [comment] 2020-10-07 07:39
@agustingabiola Thanks and thank you for reporting. I think this is a duplicate of #109 right?

**Comment by agustingabiola** [comment] 2020-10-07 13:01
> @agustingabiola Thanks and thank you for reporting. I think this is a duplicate of #109 right?

Indeed, I missed that issue while looking for an existing one before reporting. I will close it. Thank you and good day.

**Closed** 2020-10-08 08:31 UTC
